### ISSUE TITLE
getting in touch

### ISSUE THREAD

**Issue by bubnikv** [eadf/boostvoronoi.rs#3]
Hello.

I have seen a lot of activity around the boost::polygon::voronoi. Kudos, you certainly have put a lot of effort into understanding the complex implementation by Alexii Sydorchuck.

I am with Prusa Research, we use boost::polygon::voronoi in our 3D printing application PrusaSlicer for multiple purposes. Thus I am following your efforts with excitement.

I wonder what your motivation is. Are you doing the work on voronoi generator just for fun?
Just for [eadf/toxicblend.rs: gRPC blender-addon written in Rust (github.com)](https://github.com/eadf/toxicblend.rs) ?
Or are you planning to use it for some commercial product?

How stable is your Rust port? Do you think you fixed some of the bugs in the boost::polygon::voronoi code?

BTW It seems to me that there are some bugs, that occur for vertical or nearly vertical segments, thus just rotating the input polygon by a random angle helps.

Good luck,
Vojtech Bubnik
Prusa Resarch

**Comment by eadf** [comment]
Hello Vojtech, Thank you for reaching out and showing interest in my project.

To answer your questions, my motivations are just personal entertainment and to learn more about Rust. So I'm only planning on using the port in projects like toxicblend and [hallr](https://github.com/eadf/hallr). I don't have plans to use it for a commercial product at this time, but that said, I would not mind a collaboration with someone interested in using the port in a commercial product. If you have any ideas or proposals in mind, feel free to discuss them.

I would say that my port is nearly as stable as the boost::polygon::voronoi version is, but that's not saying very much 
as it does not take much effort to find problems in the boost version as well. That said, it seems like i have inadvertently introduced some new bugs #4.

Your observation about bugs occurring for vertical or nearly vertical segments is interesting, and I will investigate this further, maybe problems can be detected and, optionally, solved automatically by bumping the input a little.

First of all i need to get rid of the linked list beachline map workaround #1, either by fixing the actual problem inherited from boost, or by implementing a faster map structure. Secondly i will rewrite the half-edge structure, maybe something similar to the spade crate.

Thank you for your interest in the project. If you have any more questions or suggestions, please feel free to share them.

Best regards,
Eadf (lacklustr@protonmail.com)
